//SSID and password
#ifndef SSID
#define SSID "IOT-TEAM"
#define PWD  "#0h.dear#"
#endif



#define READ_API 7Y1VNND5QHG4BJQZ
#define WRITE_API 219PKOIIE9QMF1QA


#define SECRET_MQTT_USERNAME "MysXHiAUFB4dMRU8LwgOExI"
#define SECRET_MQTT_CLIENT_ID "MysXHiAUFB4dMRU8LwgOExI"
#define SECRET_MQTT_PASSWORD "C7hsG7Tsyazr9EznP6zexLJi"